### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [Zubenna/project-bubble-sort#2]
Consider these improvements:

1. Keep consistency of your ways of operating
1.1. Your bubble sort and bubble sort by should not be very different
1.2. Try to use the same loop way
2. Try to test your methods to order in ascending order
3. Do not forget comments before submitting the project for review

**Comment by Zubenna** [comment]
Recommendations have been implemented.

**Comment by Zubenna** [comment]
Recommendations have been implemented.
